### ISSUE TITLE
[PROPOSAL] - dual speed release tempo

### ISSUE THREAD

**Issue by michaelneale** [TBD54566975/collaboration#45]
_Desired outcome_

It is common for consumer and even enterprise software to have a choice of release tempos: a slower moving but "stable" and perhaps a more frequent or "nightly" release schedule. 

_Current Gaps_

There aren't regular releases of all the components yet, so would be good to agree on what that might look like. Ideally they are released together (vs each project or component on its own, if possible).

_Implementation Suggestions (optional)_

Make main branch be the "nightly" - and a versioned strategy for stable releases (perhaps this can be flipped around? open to discussion)

**Comment by ALRubinger** [comment]
You're considering this for Platform releases or the components themselves?

I'd love to see a Bill-of-Materials (BOM) type project which brings the Web5 Platform components together. That could identify versions as a set of dependencies and have structure:

* `main` - Latest development branch where components propose upgrades to the platform and are checked by system tests
* `stable` - Lastest stable branch from which releases are cut
* `development` - Branch for next-gen ideas, or perhaps even branch-per-exploratory feature?

Does a BOM-type project start to address what you're raising here?

**Comment by michaelneale** [comment]
good question - haven't thought about specifics. I was thinking mostly components to start with, but really it applies to whole platform. 

I think that 3 "speed" type of thing could work (I want to get basic automation happening first), but I am not quite sure how a BOM fits in, I think (but not sure) it is sort of orthogonal: something attesting where all the commits and libs came from so people can feel more confident, I guess it would be part of each automated release.

**Comment by ALRubinger** [comment]
+100 on basic automation first:

* CI
* Then CD (in our case, likely releases to repos)

For BOMs, a great discussion to have would be about what defines "the platform". Right now @nitro-neal's work in [`web5-components`](https://github.com/TBD54566975/web5-components-tests) brings things together, which effectively is a dependency set as a BOM. A cool place to get this to might be to externalize the what defines the "platform" so that the tests could run against different platform versions, validating them along the way.

Throwing thoughts here for a more comprehensive discussion; if there's an AI we want to propose from this here, I'm all ears!
